## TASK-3

## 2. Each student member creates notebooks to read the Enrichment data and displays them on a notebook.

Import pandas library in order to read the census demoraphic dataset and perform analysis on this dataset

In [1]:
import pandas as pd

Reading the raw census demographic dataset and displaying the dataset

In [2]:
temp = pd.read_csv("../../../../data/stage_1/ACSDP5Y2019.DP05_data_with_overlays_2022-01-14T190209.csv",low_memory=False)
cn_demographic = pd.DataFrame(temp)
cn_demographic

,DP05_0001E,DP05_0001M,DP05_0001PE,DP05_0001PM,DP05_0002E,DP05_0002M,DP05_0002PE,DP05_0002PM,DP05_0003E,DP05_0003M,...,DP05_0088E,DP05_0088M,DP05_0088PE,DP05_0088PM,DP05_0089E,DP05_0089M,DP05_0089PE,DP05_0089PM,GEO_ID,NAME
0,Estimate!!SEX AND AGE!!Total population,Margin of Error!!SEX AND AGE!!Total population,Percent!!SEX AND AGE!!Total population,Percent Margin of Error!!SEX AND AGE!!Total po...,Estimate!!SEX AND AGE!!Total population!!Male,Margin of Error!!SEX AND AGE!!Total population...,Percent!!SEX AND AGE!!Total population!!Male,Percent Margin of Error!!SEX AND AGE!!Total po...,Estimate!!SEX AND AGE!!Total population!!Female,Margin of Error!!SEX AND AGE!!Total population...,...,"Estimate!!CITIZEN, VOTING AGE POPULATION!!Citi...","Margin of Error!!CITIZEN, VOTING AGE POPULATIO...","Percent!!CITIZEN, VOTING AGE POPULATION!!Citiz...","Percent Margin of Error!!CITIZEN, VOTING AGE P...","Estimate!!CITIZEN, VOTING AGE POPULATION!!Citi...","Margin of Error!!CITIZEN, VOTING AGE POPULATIO...","Percent!!CITIZEN, VOTING AGE POPULATION!!Citiz...","Percent Margin of Error!!CITIZEN, VOTING AGE P...",id,Geographic Area Name
1,55380,*****,55380,(X),26934,166,48.6,0.3,28446,166,...,19823,189,47.6,0.2,21824,97,52.4,0.2,0500000US01001,"Autauga County, Alabama"
2,212830,*****,212830,(X),103496,233,48.6,0.1,109334,233,...,77958,410,47.9,0.2,84925,403,52.1,0.2,0500000US01003,"Baldwin County, Alabama"
3,25361,*****,25361,(X),13421,80,52.9,0.3,11940,80,...,10529,80,53.4,0.3,9199,69,46.6,0.3,0500000US01005,"Barbour County, Alabama"
4,22493,*****,22493,(X),12150,193,54.0,0.9,10343,193,...,9469,102,53.6,0.4,8193,43,46.4,0.4,0500000US01007,"Bibb County, Alabama"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3216,52192,*****,52192,(X),24963,*****,47.8,*****,27229,*****,...,19564,83,47.0,0.1,22062,80,53.0,0.1,0500000US72145,"Vega Baja Municipio, Puerto Rico"
3217,8642,*****,8642,(X),4277,103,49.5,1.2,4365,103,...,3488,4,50.3,0.1,3449,16,49.7,0.1,0500000US72147,"Vieques Municipio, Puerto Rico"
3218,22403,*****,22403,(X),10856,*****,48.5,*****,11547,*****,...,8282,61,47.4,0.2,9197,2,52.6,0.2,0500000US72149,"Villalba Municipio, Puerto Rico"
3219,33499,*****,33499,(X),16202,*****,48.4,*****,17297,*****,...,12860,4,47.6,0.1,14129,41,52.4,0.1,0500000US72151,"Yabucoa Municipio, Puerto Rico"
3220,35428,*****,35428,(X),16959,*****,47.9,*****,18469,*****,...,13413,25,46.8,0.1,15223,14,53.2,0.1,0500000US72153,"Yauco Municipio, Puerto Rico"

## 3. Each student member performs initial merges with the COVID-19 data using the variables in the Enrichment data.

Removing the 0th row as it is having another column descriptions

In [3]:
cn_demographic.drop(cn_demographic.index[0],inplace =True)
cn_demographic

,DP05_0001E,DP05_0001M,DP05_0001PE,DP05_0001PM,DP05_0002E,DP05_0002M,DP05_0002PE,DP05_0002PM,DP05_0003E,DP05_0003M,...,DP05_0088E,DP05_0088M,DP05_0088PE,DP05_0088PM,DP05_0089E,DP05_0089M,DP05_0089PE,DP05_0089PM,GEO_ID,NAME
1,55380,*****,55380,(X),26934,166,48.6,0.3,28446,166,...,19823,189,47.6,0.2,21824,97,52.4,0.2,0500000US01001,"Autauga County, Alabama"
2,212830,*****,212830,(X),103496,233,48.6,0.1,109334,233,...,77958,410,47.9,0.2,84925,403,52.1,0.2,0500000US01003,"Baldwin County, Alabama"
3,25361,*****,25361,(X),13421,80,52.9,0.3,11940,80,...,10529,80,53.4,0.3,9199,69,46.6,0.3,0500000US01005,"Barbour County, Alabama"
4,22493,*****,22493,(X),12150,193,54.0,0.9,10343,193,...,9469,102,53.6,0.4,8193,43,46.4,0.4,0500000US01007,"Bibb County, Alabama"
5,57681,*****,57681,(X),28495,142,49.4,0.2,29186,142,...,20833,182,48.8,0.3,21889,168,51.2,0.3,0500000US01009,"Blount County, Alabama"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3216,52192,*****,52192,(X),24963,*****,47.8,*****,27229,*****,...,19564,83,47.0,0.1,22062,80,53.0,0.1,0500000US72145,"Vega Baja Municipio, Puerto Rico"
3217,8642,*****,8642,(X),4277,103,49.5,1.2,4365,103,...,3488,4,50.3,0.1,3449,16,49.7,0.1,0500000US72147,"Vieques Municipio, Puerto Rico"
3218,22403,*****,22403,(X),10856,*****,48.5,*****,11547,*****,...,8282,61,47.4,0.2,9197,2,52.6,0.2,0500000US72149,"Villalba Municipio, Puerto Rico"
3219,33499,*****,33499,(X),16202,*****,48.4,*****,17297,*****,...,12860,4,47.6,0.1,14129,41,52.4,0.1,0500000US72151,"Yabucoa Municipio, Puerto Rico"
3220,35428,*****,35428,(X),16959,*****,47.9,*****,18469,*****,...,13413,25,46.8,0.1,15223,14,53.2,0.1,0500000US72153,"Yauco Municipio, Puerto Rico"

Removing the unwanted columns for better understanding of dataset.

In [4]:
cn_demographic=cn_demographic.drop(cn_demographic.columns[cn_demographic.columns.str.contains("PM")], axis=1)
cn_demographic=cn_demographic.drop(cn_demographic.columns[cn_demographic.columns.str.contains("PE")], axis=1)
#cn_demographic=cn_demographic.drop(cn_demographic.columns[cn_demographic.columns.str.contains("M")], axis=1)
#cn_demographic

Initial datatypes of the census demographic dataset

In [5]:
cn_demographic.dtypes

DP05_0001E    object
DP05_0001M    object
DP05_0002E    object
DP05_0002M    object
DP05_0003E    object
               ...
DP05_0088M    object
DP05_0089E    object
DP05_0089M    object
GEO_ID        object
NAME          object
Length: 180, dtype: object

In order to merge the large covid dataset with the census demographic set we need to search for the common variables in both data sets. 

In enrichment dataset there is a column GEO_ID which contains unique five digit countyFIPS code. 

So, slice the GEO_ID to get the countyFIPS as it one of the common variable with the large covid dataset.

Change the datatype of GEO_ID from object to int64 as it should match with datatype in large covid dataset and rename the column name from GEO_ID to countyFIPS

In [6]:
cn_demographic['GEO_ID']= cn_demographic['GEO_ID'].str.slice(start=9)
cn_demographic = cn_demographic.astype({'GEO_ID' : 'int64'})
cn_demographic = cn_demographic[cn_demographic.GEO_ID<72001]
cn_demographic.rename(columns = {'GEO_ID':'countyFIPS'},inplace = True)
cn_demographic

,DP05_0001E,DP05_0001M,DP05_0002E,DP05_0002M,DP05_0003E,DP05_0003M,DP05_0004E,DP05_0004M,DP05_0005E,DP05_0005M,...,DP05_0086E,DP05_0086M,DP05_0087E,DP05_0087M,DP05_0088E,DP05_0088M,DP05_0089E,DP05_0089M,countyFIPS,NAME
1,55380,*****,26934,166,28446,166,94.7,1.1,3217,107,...,23493,83,41647,224,19823,189,21824,97,1001,"Autauga County, Alabama"
2,212830,*****,103496,233,109334,233,94.7,0.4,11689,30,...,114164,219,162883,640,77958,410,84925,403,1003,"Baldwin County, Alabama"
3,25361,*****,13421,80,11940,80,112.4,1.4,1349,26,...,12013,143,19728,107,10529,80,9199,69,1005,"Barbour County, Alabama"
4,22493,*****,12150,193,10343,193,117.5,4.1,1315,170,...,9185,68,17662,87,9469,102,8193,43,1007,"Bibb County, Alabama"
5,57681,*****,28495,142,29186,142,97.6,1.0,3432,71,...,24323,67,42722,233,20833,182,21889,168,1009,"Blount County, Alabama"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3138,43521,*****,22471,207,21050,207,106.8,2.0,3015,85,...,19771,66,30818,313,15990,217,14828,277,56037,"Sweetwater County, Wyoming"
3139,23280,*****,12325,350,10955,350,112.5,6.8,1161,188,...,13848,89,16775,355,8561,218,8214,245,56039,"Teton County, Wyoming"
3140,20479,*****,10406,115,10073,115,103.3,2.3,1498,73,...,9041,57,14041,170,7090,90,6951,138,56041,"Uinta County, Wyoming"
3141,8027,*****,4065,91,3962,91,102.6,4.6,461,75,...,3860,46,5997,99,3043,74,2954,65,56043,"Washakie County, Wyoming"
3142,7049,*****,3719,61,3330,61,111.7,3.9,393,*****,...,3562,45,5474,61,2907,40,2567,39,56045,"Weston County, Wyoming"

Spliting the NAME column in the enrichment dataset which contains both County Name and State

As the large covid dataset also contains County Name and State variables

In [7]:
cn_demographic[['County Name','State']]= cn_demographic['NAME'].str.split(',',1,expand=True)
cn_demographic

,DP05_0001E,DP05_0001M,DP05_0002E,DP05_0002M,DP05_0003E,DP05_0003M,DP05_0004E,DP05_0004M,DP05_0005E,DP05_0005M,...,DP05_0087E,DP05_0087M,DP05_0088E,DP05_0088M,DP05_0089E,DP05_0089M,countyFIPS,NAME,County Name,State
1,55380,*****,26934,166,28446,166,94.7,1.1,3217,107,...,41647,224,19823,189,21824,97,1001,"Autauga County, Alabama",Autauga County,Alabama
2,212830,*****,103496,233,109334,233,94.7,0.4,11689,30,...,162883,640,77958,410,84925,403,1003,"Baldwin County, Alabama",Baldwin County,Alabama
3,25361,*****,13421,80,11940,80,112.4,1.4,1349,26,...,19728,107,10529,80,9199,69,1005,"Barbour County, Alabama",Barbour County,Alabama
4,22493,*****,12150,193,10343,193,117.5,4.1,1315,170,...,17662,87,9469,102,8193,43,1007,"Bibb County, Alabama",Bibb County,Alabama
5,57681,*****,28495,142,29186,142,97.6,1.0,3432,71,...,42722,233,20833,182,21889,168,1009,"Blount County, Alabama",Blount County,Alabama
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3138,43521,*****,22471,207,21050,207,106.8,2.0,3015,85,...,30818,313,15990,217,14828,277,56037,"Sweetwater County, Wyoming",Sweetwater County,Wyoming
3139,23280,*****,12325,350,10955,350,112.5,6.8,1161,188,...,16775,355,8561,218,8214,245,56039,"Teton County, Wyoming",Teton County,Wyoming
3140,20479,*****,10406,115,10073,115,103.3,2.3,1498,73,...,14041,170,7090,90,6951,138,56041,"Uinta County, Wyoming",Uinta County,Wyoming
3141,8027,*****,4065,91,3962,91,102.6,4.6,461,75,...,5997,99,3043,74,2954,65,56043,"Washakie County, Wyoming",Washakie County,Wyoming
3142,7049,*****,3719,61,3330,61,111.7,3.9,393,*****,...,5474,61,2907,40,2567,39,56045,"Weston County, Wyoming",Weston County,Wyoming

Mapping the State Name to two letters as it matches with the State column in the large covid dataset

In [8]:
map_state = {' Alaska' : 'AK', ' Alabama' : 'AL', ' Arkansas' : 'AR', ' American Samoa' : 'AS', ' Arizona' : 'AZ', ' California' : 'CA', ' Colorado' : 'CO', ' Connecticut' : 'CT', ' District of Columbia' : 'DC', ' Delaware' : 'DE', ' Florida' : 'FL',
' Georgia' : 'GA', ' Guam' : 'GU', ' Hawaii' : 'HI', ' Iowa' : 'IA', ' Idaho' : 'ID', ' Illinois' : 'IL', ' Indiana' : 'IN',
' Kansas' : 'KS', ' Kentucky' : 'KY', ' Louisiana' : 'LA', ' Massachusetts' : 'MA', ' Maryland' : 'MD', ' Maine' : 'ME', ' Michigan' : 'MI',
' Minnesota' : 'MN', ' Missouri' : 'MO', ' Northern Mariana Islands' : 'MP', ' Mississippi' : 'MS', ' Montana' : 'MT', ' National' : 'NA',
' North Carolina' : 'NC', ' North Dakota' : 'ND', ' Nebraska' : 'NE', ' New Hampshire' : 'NH', ' New Jersey' : 'NJ',
' New Mexico' : 'NM', ' Nevada' : 'NV', ' New York' : 'NY', ' Ohio' : 'OH', ' Oklahoma' : 'OK', ' Oregon' : 'OR', ' Pennsylvania' : 'PA',
' Puerto Rico' : 'PR', ' Rhode Island' : 'RI', ' South Carolina' : 'SC', ' South Dakota' : 'SD', ' Tennessee' : 'TN',
' Texas' : 'TX', ' Utah' : 'UT', ' Virginia' : 'VA', ' Virgin Islands' : 'VI', ' Vermont' : 'VT', ' Washington' : 'WA', ' Wisconsin' : 'WI',
' West Virginia' : 'WV', ' Wyoming' : 'WY',}
cn_demographic['State'] = cn_demographic.State.map(map_state)
cn_demographic

,DP05_0001E,DP05_0001M,DP05_0002E,DP05_0002M,DP05_0003E,DP05_0003M,DP05_0004E,DP05_0004M,DP05_0005E,DP05_0005M,...,DP05_0087E,DP05_0087M,DP05_0088E,DP05_0088M,DP05_0089E,DP05_0089M,countyFIPS,NAME,County Name,State
1,55380,*****,26934,166,28446,166,94.7,1.1,3217,107,...,41647,224,19823,189,21824,97,1001,"Autauga County, Alabama",Autauga County,AL
2,212830,*****,103496,233,109334,233,94.7,0.4,11689,30,...,162883,640,77958,410,84925,403,1003,"Baldwin County, Alabama",Baldwin County,AL
3,25361,*****,13421,80,11940,80,112.4,1.4,1349,26,...,19728,107,10529,80,9199,69,1005,"Barbour County, Alabama",Barbour County,AL
4,22493,*****,12150,193,10343,193,117.5,4.1,1315,170,...,17662,87,9469,102,8193,43,1007,"Bibb County, Alabama",Bibb County,AL
5,57681,*****,28495,142,29186,142,97.6,1.0,3432,71,...,42722,233,20833,182,21889,168,1009,"Blount County, Alabama",Blount County,AL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3138,43521,*****,22471,207,21050,207,106.8,2.0,3015,85,...,30818,313,15990,217,14828,277,56037,"Sweetwater County, Wyoming",Sweetwater County,WY
3139,23280,*****,12325,350,10955,350,112.5,6.8,1161,188,...,16775,355,8561,218,8214,245,56039,"Teton County, Wyoming",Teton County,WY
3140,20479,*****,10406,115,10073,115,103.3,2.3,1498,73,...,14041,170,7090,90,6951,138,56041,"Uinta County, Wyoming",Uinta County,WY
3141,8027,*****,4065,91,3962,91,102.6,4.6,461,75,...,5997,99,3043,74,2954,65,56043,"Washakie County, Wyoming",Washakie County,WY
3142,7049,*****,3719,61,3330,61,111.7,3.9,393,*****,...,5474,61,2907,40,2567,39,56045,"Weston County, Wyoming",Weston County,WY

Even after deleting the unwanted columns initially still the dataset is too huge.

So for now selecting the limited columns to perform particular level of analysis with the large covid dataset.

In future I may add or delete the columns accordingly.

In [9]:
cn_demographic = cn_demographic[['countyFIPS','County Name','State','DP05_0001E','DP05_0002E','DP05_0003E','DP05_0004E','DP05_0005E','DP05_0006E','DP05_0007E','DP05_0008E','DP05_0009E','DP05_0010E','DP05_0011E','DP05_0012E','DP05_0013E','DP05_0014E','DP05_0015E',
                                'DP05_0016E','DP05_0017E','DP05_0018E','DP05_0019E','DP05_0021E','DP05_0026E','DP05_0027E','DP05_0028E','DP05_0037E','DP05_0038E',
                                'DP05_0044E','DP05_0087E','DP05_0088E','DP05_0089E']]
#cn_demographic

Renaming the column names of the census demographic dataset for better understanding of particular column

In [10]:
cn_demographic = cn_demographic.rename(columns={'DP05_0001E':'Total population','DP05_0002E':'Males','DP05_0003E':'Females','DP05_0004E':'Sex ratio(males per 100 females)','DP05_0005E':'Under 5years','DP05_0006E':'5-9years','DP05_0007E':'10-14years','DP05_0008E':'15-19years','DP05_0009E':'20-24years','DP05_0010E':'25-34years','DP05_0011E':'35-44years','DP05_0012E':'45-54years','DP05_0013E':'55-59years','DP05_0014E':'60-64years','DP05_0015E':'65-74years',
                                'DP05_0016E':'75-84years','DP05_0017E':'85years and over','DP05_0018E':'Median age(years)','DP05_0019E':'Under 18years','DP05_0021E':'18years and over','DP05_0026E':'18years and over Male','DP05_0027E':'18years and over Female','DP05_0028E':'Sex ratio(18years and over)','DP05_0037E':'White population','DP05_0038E':'Black population',
                                'DP05_0044E':'Asian population','DP05_0087E':'Voting population','DP05_0088E':'Voting population(Male)','DP05_0089E':'Voting population(Female)'})
cn_demographic

,countyFIPS,County Name,State,Total population,Males,Females,Sex ratio(males per 100 females),Under 5years,5-9years,10-14years,...,18years and over,18years and over Male,18years and over Female,Sex ratio(18years and over),White population,Black population,Asian population,Voting population,Voting population(Male),Voting population(Female)
1,1001,Autauga County,AL,55380,26934,28446,94.7,3217,3814,3600,...,42175,20164,22011,91.6,42527,10538,573,41647,19823,21824
2,1003,Baldwin County,AL,212830,103496,109334,94.7,11689,12058,14262,...,166595,79948,86647,92.3,183471,19718,1969,162883,77958,84925
3,1005,Barbour County,AL,25361,13421,11940,112.4,1349,1622,1422,...,20054,10760,9294,115.8,11869,12066,134,19728,10529,9199
4,1007,Bibb County,AL,22493,12150,10343,117.5,1315,1219,1132,...,17862,9547,8315,114.8,17272,5014,27,17662,9469,8193
5,1009,Blount County,AL,57681,28495,29186,97.6,3432,3590,4034,...,44292,21668,22624,95.8,55062,928,212,42722,20833,21889
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3138,56037,Sweetwater County,WY,43521,22471,21050,106.8,3015,3613,3080,...,31974,16547,15427,107.3,40642,502,340,30818,15990,14828
3139,56039,Teton County,WY,23280,12325,10955,112.5,1161,1536,1241,...,18842,9750,9092,107.2,20785,290,291,16775,8561,8214
3140,56041,Uinta County,WY,20479,10406,10073,103.3,1498,1890,1606,...,14506,7294,7212,101.1,19132,23,32,14041,7090,6951
3141,56043,Washakie County,WY,8027,4065,3962,102.6,461,515,543,...,6049,3068,2981,102.9,7204,3,0,5997,3043,2954
3142,56045,Weston County,WY,7049,3719,3330,111.7,393,590,258,...,5567,2952,2615,112.9,6867,16,54,5474,2907,2567

Finding the datatypes of modified census demographic dataset

In [11]:
cn_demographic.dtypes

countyFIPS                           int64
County Name                         object
State                               object
Total population                    object
Males                               object
Females                             object
Sex ratio(males per 100 females)    object
Under 5years                        object
5-9years                            object
10-14years                          object
15-19years                          object
20-24years                          object
25-34years                          object
35-44years                          object
45-54years                          object
55-59years                          object
60-64years                          object
65-74years                          object
75-84years                          object
85years and over                    object
Median age(years)                   object
Under 18years                       object
18years and over                    object
18years and over Male               object
18years and over Female             object
Sex ratio(18years and over)         object
White population                    object
Black population                    object
Asian population                    object
Voting population                   object
Voting population(Male)             object
Voting population(Female)           object
dtype: object

Reading the combined covid dataset and displaying the dataset

In [12]:
cn_demographic.to_csv("../../../../data/stage_1/census1.csv",index = False)

In [13]:
temp1 = pd.read_csv("../../../../data/stage_1/large_covid.csv")
large_covid = pd.DataFrame(temp1)
large_covid

,countyFIPS,County Name_x,State,StateFIPS,2020-01-22_x,2020-01-23_x,2020-01-24_x,2020-01-25_x,2020-01-26_x,2020-01-27_x,...,2021-08-09_y,2021-08-10_y,2021-08-11_y,2021-08-12_y,2021-08-13_y,2021-08-14_y,2021-08-15_y,2021-08-16_y,County Name_y,population
0,0,Statewide Unallocated,AL,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,Statewide Unallocated,0
1,1001,Autauga County,AL,1,0,0,0,0,0,0,...,114,114,114,114,114,114,114,114,Autauga County,55869
2,1003,Baldwin County,AL,1,0,0,0,0,0,0,...,330,332,338,342,344,344,344,347,Baldwin County,223234
3,1005,Barbour County,AL,1,0,0,0,0,0,0,...,63,63,64,64,65,65,65,65,Barbour County,24686
4,1007,Bibb County,AL,1,0,0,0,0,0,0,...,66,66,67,67,67,67,67,67,Bibb County,22394
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3188,56037,Sweetwater County,WY,56,0,0,0,0,0,0,...,45,45,45,45,45,45,45,45,Sweetwater County,42343
3189,56039,Teton County,WY,56,0,0,0,0,0,0,...,11,11,11,11,11,11,11,11,Teton County,23464
3190,56041,Uinta County,WY,56,0,0,0,0,0,0,...,14,14,14,14,14,14,14,14,Uinta County,20226
3191,56043,Washakie County,WY,56,0,0,0,0,0,0,...,26,26,26,26,26,26,26,26,Washakie County,7805
3192,56045,Weston County,WY,56,0,0,0,0,0,0,...,6,6,6,6,6,6,6,6,Weston County,6927

Dropping the additional column County Name_y  in the large covid dataset

Renaming the column County Name_x to County Name in order to perform merge.

In [14]:
large_covid.drop(columns=['County Name_y'],axis=1,inplace =True)
large_covid.rename(columns={'County Name_x':'County Name'},inplace =True)
#large_covid = large_covid[large_covid["County Name"]!= "Statewide Unallocated"]
large_covid

,countyFIPS,County Name,State,StateFIPS,2020-01-22_x,2020-01-23_x,2020-01-24_x,2020-01-25_x,2020-01-26_x,2020-01-27_x,...,2021-08-08_y,2021-08-09_y,2021-08-10_y,2021-08-11_y,2021-08-12_y,2021-08-13_y,2021-08-14_y,2021-08-15_y,2021-08-16_y,population
0,0,Statewide Unallocated,AL,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1001,Autauga County,AL,1,0,0,0,0,0,0,...,114,114,114,114,114,114,114,114,114,55869
2,1003,Baldwin County,AL,1,0,0,0,0,0,0,...,330,330,332,338,342,344,344,344,347,223234
3,1005,Barbour County,AL,1,0,0,0,0,0,0,...,63,63,63,64,64,65,65,65,65,24686
4,1007,Bibb County,AL,1,0,0,0,0,0,0,...,66,66,66,67,67,67,67,67,67,22394
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3188,56037,Sweetwater County,WY,56,0,0,0,0,0,0,...,45,45,45,45,45,45,45,45,45,42343
3189,56039,Teton County,WY,56,0,0,0,0,0,0,...,11,11,11,11,11,11,11,11,11,23464
3190,56041,Uinta County,WY,56,0,0,0,0,0,0,...,14,14,14,14,14,14,14,14,14,20226
3191,56043,Washakie County,WY,56,0,0,0,0,0,0,...,26,26,26,26,26,26,26,26,26,7805
3192,56045,Weston County,WY,56,0,0,0,0,0,0,...,6,6,6,6,6,6,6,6,6,6927

Finding the datatypes of large covid dataset to confirm whether the common columns are matching with the census demographic dataset

In [15]:
large_covid.dtypes

countyFIPS       int64
County Name     object
State           object
StateFIPS        int64
2020-01-22_x     int64
                 ...
2021-08-13_y     int64
2021-08-14_y     int64
2021-08-15_y     int64
2021-08-16_y     int64
population       int64
Length: 1151, dtype: object

In [16]:
large_covid.shape   #Finding the shape of the large covid dataset

(3193, 1151)

Applying strip to County Name columns in the both data sets to remove all the unwanted spaces so that it merges correctly.

In [17]:
cn_demographic.drop(columns=['Total population'],axis=1,inplace=True)
cn_demographic['County Name']= cn_demographic['County Name'].apply(lambda x: x.strip())
large_covid['County Name']= large_covid['County Name'].apply(lambda x: x.strip())
cn_demographic

,countyFIPS,County Name,State,Males,Females,Sex ratio(males per 100 females),Under 5years,5-9years,10-14years,15-19years,...,18years and over,18years and over Male,18years and over Female,Sex ratio(18years and over),White population,Black population,Asian population,Voting population,Voting population(Male),Voting population(Female)
1,1001,Autauga County,AL,26934,28446,94.7,3217,3814,3600,3812,...,42175,20164,22011,91.6,42527,10538,573,41647,19823,21824
2,1003,Baldwin County,AL,103496,109334,94.7,11689,12058,14262,12831,...,166595,79948,86647,92.3,183471,19718,1969,162883,77958,84925
3,1005,Barbour County,AL,13421,11940,112.4,1349,1622,1422,1412,...,20054,10760,9294,115.8,11869,12066,134,19728,10529,9199
4,1007,Bibb County,AL,12150,10343,117.5,1315,1219,1132,1400,...,17862,9547,8315,114.8,17272,5014,27,17662,9469,8193
5,1009,Blount County,AL,28495,29186,97.6,3432,3590,4034,3622,...,44292,21668,22624,95.8,55062,928,212,42722,20833,21889
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3138,56037,Sweetwater County,WY,22471,21050,106.8,3015,3613,3080,3246,...,31974,16547,15427,107.3,40642,502,340,30818,15990,14828
3139,56039,Teton County,WY,12325,10955,112.5,1161,1536,1241,944,...,18842,9750,9092,107.2,20785,290,291,16775,8561,8214
3140,56041,Uinta County,WY,10406,10073,103.3,1498,1890,1606,1465,...,14506,7294,7212,101.1,19132,23,32,14041,7090,6951
3141,56043,Washakie County,WY,4065,3962,102.6,461,515,543,575,...,6049,3068,2981,102.9,7204,3,0,5997,3043,2954
3142,56045,Weston County,WY,3719,3330,111.7,393,590,258,368,...,5567,2952,2615,112.9,6867,16,54,5474,2907,2567

Merging large covid and demographic datasets on countyFIPS, County Name and State(Initial Merge)

In [18]:
final_merge = pd.merge(large_covid,cn_demographic,on=['countyFIPS','County Name','State'])
final_merge

,countyFIPS,County Name,State,StateFIPS,2020-01-22_x,2020-01-23_x,2020-01-24_x,2020-01-25_x,2020-01-26_x,2020-01-27_x,...,18years and over,18years and over Male,18years and over Female,Sex ratio(18years and over),White population,Black population,Asian population,Voting population,Voting population(Male),Voting population(Female)
0,1001,Autauga County,AL,1,0,0,0,0,0,0,...,42175,20164,22011,91.6,42527,10538,573,41647,19823,21824
1,1003,Baldwin County,AL,1,0,0,0,0,0,0,...,166595,79948,86647,92.3,183471,19718,1969,162883,77958,84925
2,1005,Barbour County,AL,1,0,0,0,0,0,0,...,20054,10760,9294,115.8,11869,12066,134,19728,10529,9199
3,1007,Bibb County,AL,1,0,0,0,0,0,0,...,17862,9547,8315,114.8,17272,5014,27,17662,9469,8193
4,1009,Blount County,AL,1,0,0,0,0,0,0,...,44292,21668,22624,95.8,55062,928,212,42722,20833,21889
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3082,56037,Sweetwater County,WY,56,0,0,0,0,0,0,...,31974,16547,15427,107.3,40642,502,340,30818,15990,14828
3083,56039,Teton County,WY,56,0,0,0,0,0,0,...,18842,9750,9092,107.2,20785,290,291,16775,8561,8214
3084,56041,Uinta County,WY,56,0,0,0,0,0,0,...,14506,7294,7212,101.1,19132,23,32,14041,7090,6951
3085,56043,Washakie County,WY,56,0,0,0,0,0,0,...,6049,3068,2981,102.9,7204,3,0,5997,3043,2954
3086,56045,Weston County,WY,56,0,0,0,0,0,0,...,5567,2952,2615,112.9,6867,16,54,5474,2907,2567

Writing the merged data to covid_census csv file

In [19]:
final_merge.to_csv("../../../../data/stage_1/covid_census.csv",index = False)

In [20]:
temp2 = pd.read_csv("../../../../data/stage_1/long_large_covid.csv")
long_large_covid = pd.DataFrame(temp2)
long_large_covid

,countyFIPS,County Name,State,StateFIPS,Date,Cases,Death,Population
0,0,Statewide Unallocated,AL,1,2020-01-22,0,0,0
1,0,Statewide Unallocated,AL,1,2020-01-23,0,0,0
2,0,Statewide Unallocated,AL,1,2020-01-24,0,0,0
3,0,Statewide Unallocated,AL,1,2020-01-25,0,0,0
4,0,Statewide Unallocated,AL,1,2020-01-26,0,0,0
...,...,...,...,...,...,...,...,...
1829584,56045,Weston County,WY,56,2021-08-12,700,6,6927
1829585,56045,Weston County,WY,56,2021-08-13,700,6,6927
1829586,56045,Weston County,WY,56,2021-08-14,705,6,6927
1829587,56045,Weston County,WY,56,2021-08-15,705,6,6927
1829588,56045,Weston County,WY,56,2021-08-16,705,6,6927

In [21]:
cn_demographic['County Name']= cn_demographic['County Name'].apply(lambda x: x.strip())
long_large_covid = long_large_covid[long_large_covid['County Name'] != 'Statewide Unallocated']
long_large_covid['County Name']= long_large_covid['County Name'].apply(lambda x: x.strip())
cn_demographic

/var/folders/q4/d0z8tvws1d3fd6zmyfthqwv40000gn/T/ipykernel_41266/2920063868.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  long_large_covid['County Name']= long_large_covid['County Name'].apply(lambda x: x.strip())

,countyFIPS,County Name,State,Males,Females,Sex ratio(males per 100 females),Under 5years,5-9years,10-14years,15-19years,...,18years and over,18years and over Male,18years and over Female,Sex ratio(18years and over),White population,Black population,Asian population,Voting population,Voting population(Male),Voting population(Female)
1,1001,Autauga County,AL,26934,28446,94.7,3217,3814,3600,3812,...,42175,20164,22011,91.6,42527,10538,573,41647,19823,21824
2,1003,Baldwin County,AL,103496,109334,94.7,11689,12058,14262,12831,...,166595,79948,86647,92.3,183471,19718,1969,162883,77958,84925
3,1005,Barbour County,AL,13421,11940,112.4,1349,1622,1422,1412,...,20054,10760,9294,115.8,11869,12066,134,19728,10529,9199
4,1007,Bibb County,AL,12150,10343,117.5,1315,1219,1132,1400,...,17862,9547,8315,114.8,17272,5014,27,17662,9469,8193
5,1009,Blount County,AL,28495,29186,97.6,3432,3590,4034,3622,...,44292,21668,22624,95.8,55062,928,212,42722,20833,21889
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3138,56037,Sweetwater County,WY,22471,21050,106.8,3015,3613,3080,3246,...,31974,16547,15427,107.3,40642,502,340,30818,15990,14828
3139,56039,Teton County,WY,12325,10955,112.5,1161,1536,1241,944,...,18842,9750,9092,107.2,20785,290,291,16775,8561,8214
3140,56041,Uinta County,WY,10406,10073,103.3,1498,1890,1606,1465,...,14506,7294,7212,101.1,19132,23,32,14041,7090,6951
3141,56043,Washakie County,WY,4065,3962,102.6,461,515,543,575,...,6049,3068,2981,102.9,7204,3,0,5997,3043,2954
3142,56045,Weston County,WY,3719,3330,111.7,393,590,258,368,...,5567,2952,2615,112.9,6867,16,54,5474,2907,2567

In [22]:
final_merge_1 = pd.merge(long_large_covid,cn_demographic,on=['countyFIPS','County Name','State'])
final_merge_1

,countyFIPS,County Name,State,StateFIPS,Date,Cases,Death,Population,Males,Females,...,18years and over,18years and over Male,18years and over Female,Sex ratio(18years and over),White population,Black population,Asian population,Voting population,Voting population(Male),Voting population(Female)
0,1001,Autauga County,AL,1,2020-01-22,0,0,55869,26934,28446,...,42175,20164,22011,91.6,42527,10538,573,41647,19823,21824
1,1001,Autauga County,AL,1,2020-01-23,0,0,55869,26934,28446,...,42175,20164,22011,91.6,42527,10538,573,41647,19823,21824
2,1001,Autauga County,AL,1,2020-01-24,0,0,55869,26934,28446,...,42175,20164,22011,91.6,42527,10538,573,41647,19823,21824
3,1001,Autauga County,AL,1,2020-01-25,0,0,55869,26934,28446,...,42175,20164,22011,91.6,42527,10538,573,41647,19823,21824
4,1001,Autauga County,AL,1,2020-01-26,0,0,55869,26934,28446,...,42175,20164,22011,91.6,42527,10538,573,41647,19823,21824
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1768846,56045,Weston County,WY,56,2021-08-12,700,6,6927,3719,3330,...,5567,2952,2615,112.9,6867,16,54,5474,2907,2567
1768847,56045,Weston County,WY,56,2021-08-13,700,6,6927,3719,3330,...,5567,2952,2615,112.9,6867,16,54,5474,2907,2567
1768848,56045,Weston County,WY,56,2021-08-14,705,6,6927,3719,3330,...,5567,2952,2615,112.9,6867,16,54,5474,2907,2567
1768849,56045,Weston County,WY,56,2021-08-15,705,6,6927,3719,3330,...,5567,2952,2615,112.9,6867,16,54,5474,2907,2567
1768850,56045,Weston County,WY,56,2021-08-16,705,6,6927,3719,3330,...,5567,2952,2615,112.9,6867,16,54,5474,2907,2567

In [23]:
final_merge_1.to_csv("../../../../data/stage_1/long_covid_census.csv",index = False)